/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc2021.pkg2;

import GestionUsuario.vista.Listado;
import GestionUsuario.vista.Login_Usuario;
import GestionUsuario.vista.Registro;

/**
 *
 * @author Jose Luis
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Princiipal
     */

    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        menu_IniciarSesion = new javax.swing.JMenuItem();
        menu_CerrarSesion = new javax.swing.JMenuItem();
        menu_Gestion = new javax.swing.JMenu();
        ItemMenu_Usuario = new javax.swing.JMenu();
        subItemMenu_Registro = new javax.swing.JMenuItem();
        subItemMenu_Listado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        Inicio.setText("Inicio");

        menu_IniciarSesion.setText("Iniciar Sesion");
        menu_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_IniciarSesionActionPerformed(evt);
            }
        });
        Inicio.add(menu_IniciarSesion);

        menu_CerrarSesion.setText("Cerrar Sesión");
        menu_CerrarSesion.setEnabled(false);
        menu_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CerrarSesionActionPerformed(evt);
            }
        });
        Inicio.add(menu_CerrarSesion);

        jMenuBar1.add(Inicio);

        menu_Gestion.setText("Gestión");

        ItemMenu_Usuario.setText("Usuario");
        ItemMenu_Usuario.setEnabled(false);

        subItemMenu_Registro.setText("Registro");
        subItemMenu_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subItemMenu_RegistroActionPerformed(evt);
            }
        });
        ItemMenu_Usuario.add(subItemMenu_Registro);

        subItemMenu_Listado.setText("Listado");
        subItemMenu_Listado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subItemMenu_ListadoActionPerformed(evt);
            }
        });
        ItemMenu_Usuario.add(subItemMenu_Listado);

        menu_Gestion.add(ItemMenu_Usuario);

        jMenuBar1.add(menu_Gestion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subItemMenu_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subItemMenu_RegistroActionPerformed
//        subItemMenu_Registro.setEnabled(key);
        this.contenedor.removeAll();
        this.contenedor.updateUI();
        Registro r_usuario = new Registro();
        r_usuario.setLocation(150, 10);
        r_usuario.setSize(250, 250);
        this.contenedor.add(r_usuario);
        r_usuario.setVisible(true);
        this.contenedor.validate();
    }//GEN-LAST:event_subItemMenu_RegistroActionPerformed

    private void subItemMenu_ListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subItemMenu_ListadoActionPerformed
        // TODO add your handling code here:
//        subItemMenu_Listado.setEnabled(key);
        this.contenedor.removeAll();
        this.contenedor.updateUI();
        Listado l_usuario = new Listado();
        l_usuario.setSize(400, 160);

        this.contenedor.add(l_usuario);
        l_usuario.setVisible(true);
        this.contenedor.validate();
    }//GEN-LAST:event_subItemMenu_ListadoActionPerformed

    private void menu_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_IniciarSesionActionPerformed
        // TODO add your handling code here:
//        this.contenedor.removeAll();
//        this.contenedor.updateUI();
        Login_Usuario login = new Login_Usuario(this);
        login.setSize(280, 250);
        login.setLocationRelativeTo(this);
//        this.contenedor.add(login);
        login.setVisible(true);
        
//        this.contenedor.validate();
    }//GEN-LAST:event_menu_IniciarSesionActionPerformed

    private void menu_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CerrarSesionActionPerformed
        // TODO add your handling code here:
        activador(false);
    }//GEN-LAST:event_menu_CerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Inicio;
    private javax.swing.JMenu ItemMenu_Usuario;
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_CerrarSesion;
    private javax.swing.JMenu menu_Gestion;
    private javax.swing.JMenuItem menu_IniciarSesion;
    private javax.swing.JMenuItem subItemMenu_Listado;
    private javax.swing.JMenuItem subItemMenu_Registro;
    // End of variables declaration//GEN-END:variables
   
    public void activador(boolean key){
        menu_CerrarSesion.setEnabled(key);
        ItemMenu_Usuario.setEnabled(key);
    }
}
